### ISSUE TITLE
Using `•` is always grouping itens 

### ISSUE THREAD

**Issue by guitcastro** [mudasobwa/markright#17]
Hi, first of all. Thanks for the library.

We are currently evaluating it to use to create a custom markdown parse. We found this bug. 

```
  test "parses [different types of] line items" do
    input = """
  • item 1
  • item 2
  """

  output = {
    :article,
    %{},
    [
      {:p, %{},
       [
         {:ul, %{}, [{:li, %{}, "item 1"}, {:li, %{}, "item 2"}]},
       ]}
    ]
  }

  assert input
          |> Markright.to_ast() == output
  end

```

 ```
    left:  {:article, %{}, [{:p, %{}, [{:ul, %{}, [{:li, %{}, ["item 1", {:ul, %{}, [{:li, %{}, "item 2"}]}]}]}]}]}
    right: {:article, %{}, [{:p, %{}, [{:ul, %{}, [{:li, %{}, "item 1"}, {:li, %{}, "item 2"}]}]}]}
```

As first, I thought some commit that we did had broken it, but using the 0.5.0 version does have the same behavior. This one is being a little trick to trace.

**Comment by guitcastro** [comment]
Just an update, removing `li: {"-", [parser: Markright.Parsers.Li]}` from the syntax fix it. So it's something related with duplicated syntax.

**Comment by am-kantox** [comment]
Hi @guitcastro, thanks for the bug report.

> Package published to https://hex.pm/packages/markright/0.7.3

The last commit contains changes that both a) fix several-leads issue and b) fix `custom_parser` in `0.7.2` that I blindly merged yesterday.

Thanks for the interest in the library. I have to admit, that it was written several years ago when I was learning Elixir and I did not touch it since then. The code makes my eyes bleed sometimes, but I have to admit it’s still more or less robust and it evolves ideas of how _proper_ parsing should be done I always had in my mind.

I cannot promise I would spend _too much_ time on it, but I am definitely in making it better, so please don’t hesitate to come back with ideas/bugreports/etc.

Cheers.

**Comment by guitcastro** [comment]
Sorry for the delay, I was waiting to get the approval from the legal(to open the source code) team before posting. We ended-up creating [our own lib](https://github.com/betrybe/esperanto). Still, many thanks for the help and for the lib which inspired our implementation =)

**Comment by am-kantox** [comment]
Wow, sounds great! I’ll definitely check it out. Sometimes I regret I never had a chance to rebuild `markright` from scratch or at least fix all the glitches I am aware of.

Always welcome.
